# Generated by Django 4.0.5 on 2022-07-11 13:09

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_comentario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['-created'], 'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.RemoveField(
            model_name='cursos',
            name='Link',
        ),
        migrations.RemoveField(
            model_name='cursos',
            name='NombreTutor',
        ),
        migrations.RemoveField(
            model_name='cursos',
            name='Platafroma',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='coment',
            field=ckeditor.fields.RichTextField(verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.cursos', verbose_name='Curso Elegido'),
        ),
    ]
